import { ForumPostProps } from "../components/forumPost";

export const dummyData: Array<ForumPostProps> = [
    {
      body: "KSDJHFKJHSDKHFJKWEFWJKWEJKFJWKJEBFBKJWEJKFJBWJKEBFKBWJEFJJKWEJKFBJKWJKEFJKBWJKEBFJKBJKWEBFKJBKJWEBFKJBWKEJFBKJWBEKJFBWKJEBFKJWBEKJFBJKWBEKJFBKJWBEKJFBJKWEBFJKBWEKJFBWKJEBFKJWBEFKJWBEFKJBWKEJFBWKJEFBKWJEBFKJWEBFKJWBEFKJWBEFKJWBEFKJBWEKFJBWKEJFBKJWBEFKJWBEFKJWBEFKBWJKEBFKJBWEKJFBKJWBEFJKJWBEFKJBWKJEBFJKWBEFBJKWBEJKFBWJKEBFKJWBEKFJBWEKJFBWKJEBFKWJEBFKJWEBFKJWEB",
      heading: "HEADING",
      profileImg: "",
      publisher: "PUBLISHER",
    },
    {
      body: "KSDJHFKJHSDKHFJKWEFWJKWEJKFJWKJEBFBKJWEJKFJBWJKEBFKBWJEFJJKWEJKFBJKWJKEFJKBWJKEBFJKBJKWEBFKJBKJWEBFKJBWKEJFBKJWBEKJFBWKJEBFKJWBEKJFBJKWBEKJFBKJWBEKJFBJKWEBFJKBWEKJFBWKJEBFKJWBEFKJWBEFKJBWKEJFBWKJEFBKWJEBFKJWEBFKJWBEFKJWBEFKJWBEFKJBWEKFJBWKEJFBKJWBEFKJWBEFKJWBEFKBWJKEBFKJBWEKJFBKJWBEFJKJWBEFKJBWKJEBFJKWBEFBJKWBEJKFBWJKEBFKJWBEKFJBWEKJFBWKJEBFKWJEBFKJWEBFKJWEB",
      heading: "HEADING",
      profileImg: "",
      publisher: "PUBLISHER",
    },
    {
      body: "KSDJHFKJHSDKHFJKWEFWJKWEJKFJWKJEBFBKJWEJKFJBWJKEBFKBWJEFJJKWEJKFBJKWJKEFJKBWJKEBFJKBJKWEBFKJBKJWEBFKJBWKEJFBKJWBEKJFBWKJEBFKJWBEKJFBJKWBEKJFBKJWBEKJFBJKWEBFJKBWEKJFBWKJEBFKJWBEFKJWBEFKJBWKEJFBWKJEFBKWJEBFKJWEBFKJWBEFKJWBEFKJWBEFKJBWEKFJBWKEJFBKJWBEFKJWBEFKJWBEFKBWJKEBFKJBWEKJFBKJWBEFJKJWBEFKJBWKJEBFJKWBEFBJKWBEJKFBWJKEBFKJWBEKFJBWEKJFBWKJEBFKWJEBFKJWEBFKJWEB",
      heading: "HEADING",
      profileImg: "",
      publisher: "PUBLISHER",
    },
    {
      body: "KSDJHFKJHSDKHFJKWEFWJKWEJKFJWKJEBFBKJWEJKFJBWJKEBFKBWJEFJJKWEJKFBJKWJKEFJKBWJKEBFJKBJKWEBFKJBKJWEBFKJBWKEJFBKJWBEKJFBWKJEBFKJWBEKJFBJKWBEKJFBKJWBEKJFBJKWEBFJKBWEKJFBWKJEBFKJWBEFKJWBEFKJBWKEJFBWKJEFBKWJEBFKJWEBFKJWBEFKJWBEFKJWBEFKJBWEKFJBWKEJFBKJWBEFKJWBEFKJWBEFKBWJKEBFKJBWEKJFBKJWBEFJKJWBEFKJBWKJEBFJKWBEFBJKWBEJKFBWJKEBFKJWBEKFJBWEKJFBWKJEBFKWJEBFKJWEBFKJWEB",
      heading: "HEADING",
      profileImg: "",
      publisher: "PUBLISHER",
    },
    {
      body: "KSDJHFKJHSDKHFJKWEFWJKWEJKFJWKJEBFBKJWEJKFJBWJKEBFKBWJEFJJKWEJKFBJKWJKEFJKBWJKEBFJKBJKWEBFKJBKJWEBFKJBWKEJFBKJWBEKJFBWKJEBFKJWBEKJFBJKWBEKJFBKJWBEKJFBJKWEBFJKBWEKJFBWKJEBFKJWBEFKJWBEFKJBWKEJFBWKJEFBKWJEBFKJWEBFKJWBEFKJWBEFKJWBEFKJBWEKFJBWKEJFBKJWBEFKJWBEFKJWBEFKBWJKEBFKJBWEKJFBKJWBEFJKJWBEFKJBWKJEBFJKWBEFBJKWBEJKFBWJKEBFKJWBEKFJBWEKJFBWKJEBFKWJEBFKJWEBFKJWEB",
      heading: "HEADING",
      profileImg: "",
      publisher: "PUBLISHER",
    },
    {
      body: "KSDJHFKJHSDKHFJKWEFWJKWEJKFJWKJEBFBKJWEJKFJBWJKEBFKBWJEFJJKWEJKFBJKWJKEFJKBWJKEBFJKBJKWEBFKJBKJWEBFKJBWKEJFBKJWBEKJFBWKJEBFKJWBEKJFBJKWBEKJFBKJWBEKJFBJKWEBFJKBWEKJFBWKJEBFKJWBEFKJWBEFKJBWKEJFBWKJEFBKWJEBFKJWEBFKJWBEFKJWBEFKJWBEFKJBWEKFJBWKEJFBKJWBEFKJWBEFKJWBEFKBWJKEBFKJBWEKJFBKJWBEFJKJWBEFKJBWKJEBFJKWBEFBJKWBEJKFBWJKEBFKJWBEKFJBWEKJFBWKJEBFKWJEBFKJWEBFKJWEB",
      heading: "HEADING",
      profileImg: "",
      publisher: "PUBLISHER",
    },
    {
      body: "KSDJHFKJHSDKHFJKWEFWJKWEJKFJWKJEBFBKJWEJKFJBWJKEBFKBWJEFJJKWEJKFBJKWJKEFJKBWJKEBFJKBJKWEBFKJBKJWEBFKJBWKEJFBKJWBEKJFBWKJEBFKJWBEKJFBJKWBEKJFBKJWBEKJFBJKWEBFJKBWEKJFBWKJEBFKJWBEFKJWBEFKJBWKEJFBWKJEFBKWJEBFKJWEBFKJWBEFKJWBEFKJWBEFKJBWEKFJBWKEJFBKJWBEFKJWBEFKJWBEFKBWJKEBFKJBWEKJFBKJWBEFJKJWBEFKJBWKJEBFJKWBEFBJKWBEJKFBWJKEBFKJWBEKFJBWEKJFBWKJEBFKWJEBFKJWEBFKJWEB",
      heading: "HEADING",
      profileImg: "",
      publisher: "PUBLISHER",
    },
    {
      body: "KSDJHFKJHSDKHFJKWEFWJKWEJKFJWKJEBFBKJWEJKFJBWJKEBFKBWJEFJJKWEJKFBJKWJKEFJKBWJKEBFJKBJKWEBFKJBKJWEBFKJBWKEJFBKJWBEKJFBWKJEBFKJWBEKJFBJKWBEKJFBKJWBEKJFBJKWEBFJKBWEKJFBWKJEBFKJWBEFKJWBEFKJBWKEJFBWKJEFBKWJEBFKJWEBFKJWBEFKJWBEFKJWBEFKJBWEKFJBWKEJFBKJWBEFKJWBEFKJWBEFKBWJKEBFKJBWEKJFBKJWBEFJKJWBEFKJBWKJEBFJKWBEFBJKWBEJKFBWJKEBFKJWBEKFJBWEKJFBWKJEBFKWJEBFKJWEBFKJWEB",
      heading: "HEADING",
      profileImg: "",
      publisher: "PUBLISHER",
    },
  ];